### ISSUE TITLE
stub cookie regular expression match

### ISSUE THREAD

**Issue by wenhao** [wenhao/mushrooms#14]
```yaml
mushrooms:
  stub:
    okhttp:
      enabled: true
      stubs:
        - uri: "http://localhost:8080/stub"
          method: POST
          cookies:
            - key: "session*"
               value: "4930456C*"
          body: /stubs/stub_rest_request.json
          response: /stubs/stub_rest_response.json
```
