### ISSUE TITLE
stub request body xml match

### ISSUE THREAD

**Issue by wenhao** [wenhao/mushrooms#18]
```yaml
mushrooms:
  stub:
    okhttp:
      enabled: true
      stubs:
        - uri: "http://localhost:8080/stub"
          method: POST
          body: 
            - type: xml
               value: "<bookstore>" 
                    "   <book nationality=\"ITALIAN\" category=\"COOKING\">"
                    "       <title lang=\"en\">Everyday Italian</title>"
                    "       <author>Giada De Laurentiis</author>"
                    "       <year>2005</year>"
                    "       <price>30.00</price>"
                    "   </book>"
                    "</bookstore>"
          response: /stubs/stub_rest_response.json
```
