### ISSUE TITLE
stub request body json exactly match

### ISSUE THREAD

**Issue by wenhao** [wenhao/mushrooms#19]
```yaml
mushrooms:
  stub:
    okhttp:
      enabled: true
      stubs:
        - uri: "http://localhost:8080/stub"
          method: POST
          body: 
            - type: json
               value: "{"
                        "    \"id\": 1,"
                        "    \"name\": \"A green door\","
                        "    \"price\": 12.50,"
                        "    \"tags\": [\"home\", \"green\"]"
                        "}",
                    MatchType.STRICT
          response: /stubs/stub_rest_response.json
```
