### ISSUE TITLE
支持failover缓存过滤配置

### ISSUE THREAD

**Issue by wenhao** [wenhao/mushrooms#3]
```yaml
mushrooms:
  failover:
    enabled: true
    excludes:
      - /customer
      - http://localhost:8080/customer/bank
    headers:
      - application-specific-header
    clients:
      - resttemplate
      - okhttp
```
