### ISSUE TITLE
支持failover缓存配置

### ISSUE THREAD

**Issue by wenhao** [wenhao/mushrooms#5]
```yaml
mushrooms:
  failover:
    enabled: true
    clients:
      - resttemplate
      - okhttp
```
